name: dl
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1
  - conda-forge::matplotlib
  - conda-forge::torchinfo
  - conda-forge::tqdm
  - pip
  - pip:
      - wandb
