# 除标注[可选]之外的顶级参数变量必须保留，否则需要修改对应代码

device: "cuda:0"
seed: 1
#resume: "epoch4.pth" # 断点续训使用的检查点，从头训练时删除

data:
  root: "data/raw"

model:
  name: "Net" # 模型类名
  in_channels: 1 # 模型参数，必须严格符合其构造函数声明
  num_classes: 10

loss:
  name: 'CrossEntropyLoss' # 损失函数类名

optim:
  name: "Adam" # 优化器的类名
  lr: 0.001 # 优化器参数，必须严格符合其构造函数声明

sched: # [可选]调度器设置
  name: "CosineAnnealingLR" # 学习率调度器的类名
  T_max: 3 # 学习率调度器参数，必须严格符合其构造函数声明

train:
  epochs: 3
  batch_size: 256
  log_iter: 0 # 一个epoch内打印日志的频率，不需要时设置为零
  val_start: 2 # 开始验证的epoch，用于跳过对训练初期模型的不必要验证
  val_epoch: 3 # 使用验证集验证模型的频率
  save_epoch: 5 # 保存ckpt的频率

val:
  batch_size: 256
  log_iter: 0
  ckpt: "epoch4.pth" # 用于验证的ckpt

test:
  batch_size: 256
  log_iter: 0
  ckpt: "epoch4.pth" # 用于测试的ckpt
