proj_root: 'E:\program\DL-template'
device: 'cuda:0'

data:
  root: 'data/raw'
  num_workers: 0

model:
  in_channels: 1
  num_classes: 10

train:
  epochs: 10
  batch_size: 256
  lr: 0.001
  optimizer: 'Adam'
  save_freq: 5

eval:
  resume: 'epoch9.pth'
  batch_size: 256
