proj_root: '/path/to/project'
exp_name: 'default'

data:
  root: 'data/raw'

model:
  in_channels: 1
  num_classes: 10

train:
  device: 'cuda:0'
  epochs: 10
  batch_size: 32
  lr: 0.001
  optimizer: 'Adam'
  save_freq: 1

eval:
  device: 'cuda:0'
  resume: 'epoch.pth'
  batch_size: 1
