proj_root: 'E:\program\DL-template'
exp_name: 'default'
device: 'cuda:0'
use_wandb: true

data:
  root: 'data/raw'

model:
  in_channels: 1
  num_classes: 10

train:
  epochs: 10
  batch_size: 256
  lr: 0.001
  optimizer: 'Adam'
  save_freq: 1

eval:
  resume: 'epoch9.pth'
  batch_size: 256
